---
title: "Figures"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r parameters}
att.param <- list(n1 = 500,
                  n2 = 0,
                  b1 = 0.65,
                  b2 = 0.65,
                  k1 = 500,
                  k2 = 500,
                  a12 = 1,
                  a21 = 1,
                  a11 = 1,
                  a22 = 1,
                  del1 = 0,
                  del2 = 2)

singleWindow.time.param <- list(tau = 1/52,
                                time.invade = 0,
                                time.window = 52,
                                time.index = 520)
```

## 1. Outcomes of Model

These plots display the three outcomes of the Lotka-Volterra Competition model: endemic survival, coexistence, and invader success.

```{r Outcomes}

library(ggplot2)
library(cowplot)
library(gridExtra)

df.endemic <- alphaSim(att.param, singleWindow.time.param, ratio.max=0.5, ttb=25, do.win=FALSE)
df.coexistence <- alphaSim(att.param, singleWindow.time.param, ratio.max=1, ttb=50, do.win=FALSE)
df.invader <- alphaSim(att.param, singleWindow.time.param, ratio.max=2.0, ttb =25, do.win=FALSE)

endemic.plot <- ggplot(data=df.endemic, aes(x=time)) + 
                  geom_line(aes(y=endemic, color="Endemic")) + 
                  geom_line(aes(y=invader, color="Invader")) +
                  xlab("Time (Years)") +
                  ylab("Individuals") + theme(legend.position = "none") + ylim(c(0,600))

coexistence.plot <- ggplot(data=df.coexistence, aes(x=time)) + 
                      geom_line(aes(y=endemic, color="Endemic")) + 
                      geom_line(aes(y=invader, color="Invader")) +
                      xlab("Time (Years)") +
                      ylab("Individuals") + theme(legend.position = "none") + ylim(c(0,600))

invader.plot <- ggplot(data=df.invader, aes(x=time)) +
                  geom_line(aes(y=endemic, color="Endemic")) + 
                  geom_line(aes(y=invader, color="Invader")) +
                  xlab("Time (Years)") +
                  ylab("Individuals") + theme(legend.position="bottom") + guides(color= guide_legend(title = "Species")) + ylim(c(0,600))


legend <- get_legend(invader.plot)

grid.arrange(textGrob("Species Abundance", gp=gpar(size=32)), endemic.plot, coexistence.plot, invader.plot+theme(legend.position="none"), legend, 
             ncol=3, nrow = 3, 
             layout_matrix = rbind(c(1,1,1), c(2,3,4), c(5,5,5)),
             widths = c(10,10,10), heights = c(0.5, 2.5, 0.2))
  
```


## 2. Two Types of Realizations

```{r Realization}
df.invaderWin <- alphaSim(att.param, singleWindow.time.param, ratio.max=2, ttb=25, do.win=TRUE)
df.invaderLose <- alphaSim(att.param, singleWindow.time.param, ratio.max=0.5, ttb=25, do.win=FALSE)

df.realizations <- cbind(df.invaderWin, df.invaderLose)
colnames(df.realizations) <- c("time1", "endemic1", "invader1", "ratio1", "time2", "endemic2", "invader2", "ratio2")

ggplot(data=df.realizations, aes(x=time1)) + geom_line(aes(y=invader1, color="Invasion")) + geom_line(aes(y=invader2, color="No Invasion")) + xlab("Time (years)") + ylab("Invader Abundance") + ggtitle("Invader abundance for two types of realizations") + guides(color= guide_legend(title = "Realization")) + theme(legend.position="bottom")
```

## 3. Single Window Statistics

```{r Single Window Stats: SD}
df.test <- halfAndHalf(att.param,
                       singleWindow.time.param,
                       ttb=25,
                       halfSimulations=50,
                       fail.ratio=0.1)

df.SD <- singleWindowStat(df.data=df.test,
                          singleWindow.time.param,
                          func="sd")

endemic.data = data.frame(endemic=c(att.param[1],att.param[3],att.param[5],att.param[7],att.param[9],att.param[11]))
colnames(endemic.data) = c('Initial N', 'Birth Rate', 'Carrying Cap.', 'Initial Inter.', 'Intra.', 'Immigration')
invader.data = data.frame(invader=c(att.param[2],att.param[4],att.param[6],att.param[8],att.param[10],att.param[12]))
colnames(invader.data) = c('Initial N', 'Birth Rate', 'Carrying Cap.', 'Initial Inter.', 'Intra.', 'Immigration')
parameters = rbind(endemic.data, invader.data)
rownames(parameters) = c("endemic", 'invader')

time.parameters = as.data.frame(t(c('1 Week', '10 Years', '1 Year', '50 each')))
colnames(time.parameters) = c('Tau', 'Window Start', 'Window Length', 'Realizations')
rownames(time.parameters) = c('value')

plot <-ggplot(data=df.SD,
       aes(x=stat, y=do.win)) +
       geom_point(alpha=0.15, size=5) +
       labs(x='Standard Deviation', y="Invade?") +
       ggtitle("Standard Deviation for Successful and Unsuccessful Invasions")

grid.arrange(
  arrangeGrob(plot),
  tableGrob(parameters),
  tableGrob(time.parameters),
  layout_matrix = cbind(c(1,1,1,1,2,3),
                        c(1,1,1,1,2,3),
                        c(1,1,1,1,2,3),
                        c(1,1,1,1,2,3))
)
```
## ROC Curve for Single Stat

```{r ROC Curve}
df.rates <- ROCcurveData(df.SD, numThresholds = 75, inequality = ">")
auc <- AUC(x=df.rates$FPR, y=df.rates$TPR, method='trapezoid')
ggplot(data=df.rates, aes(x=FPR, y=TPR), color='red') + geom_point() + geom_abline(slope=1, intercept=0, linetype=3) + ggtitle("TPR vs. FPR for SD as a diagnostic") + theme(legend.position="bottom")
```
## 4. Several Statistics and Realization Types

```{r Statistics}
# increasing ratio
df.increasing <- halfAndHalf(att.param, singleWindow.time.param, ttb=25, halfSimulations=50, win.ratio=2, fail.ratio=0.1, increasing=TRUE)
# constant ratio: a12 > a21
df.constant <- halfAndHalf(att.param, singleWindow.time.param, ttb=25, halfSimulations=50, win.ratio=2, fail.ratio=0.1, increasing=FALSE)

#statistics
stats <- c("mean", "sd", "cv", "kurtosis", "skewness")
inequalities <- c(">", ">", "<", ">", ">")
windows <- c(52,104,156)
time.index=520

singleStatWindows <- function(df.data, windows, time.index, statsNum) {
  df1 <- singleWindowStat(df.data, time.window=windows[1], time.index, func=stats[statsNum])
  df2 <- singleWindowStat(df.data, time.window=windows[2], time.index, func=stats[statsNum])
  df3 <- singleWindowStat(df.data, time.window=windows[3], time.index, func=stats[statsNum])
  df.stat.type <- cbind(df1,df2,df3)
  colnames(df.stat.type) = c("do.win1", "stat1","do.win2", "stat2","do.win3", "stat3")
  return(df.stat.type)
}

dfListing <- function(df.increasing, df.constant, stats) {
  statsList = list()
  for(i in 1:length(stats)) {
    df.stat.increasing = singleStatWindows(df.increasing, windows, time.index, i)
    df.stat.constant = singleStatWindows(df.constant, windows,time.index, i)
    statsList[[i]] = df.stat.increasing
    statsList[[length(stats)+i]] = df.stat.constant
  }
  return(statsList)
}

statsList <- dfListing(df.increasing, df.constant)
```

## 5. ROC Data

```{r ROC Curves}
thresholds=100

ROCdataList <- function(statsList, thresholds, stats, windows, inequalities) {
  dataList = list()
  seqj = seq(from=1, to=length(windows)*2, by=2)
  for(i in 1:length(statsList)) {
    df = data.frame(nrow=thresholds*2)
    for(j in seqj) {
      df.stat.type.roc = ROCcurveData(statsList[[i]][j:j+1], thresholds, inequalities[i%%length(stats)])
      df.final = cbind(df,df.stat.type.roc)
    }
  }
  
  # ^^^ doesnt work :( ... yet
  
    
  #increasing
  df.mean.increasing.roc1 = ROCcurveData(statsList[[1]][1:2], thresholds, ">")
  df.mean.increasing.roc2 = ROCcurveData(statsList[[1]][3:4],thresholds, ">")
  df.mean.increasing.roc3 = ROCcurveData(statsList[[1]][5:6],thresholds, ">")
  df.mean.increasing = cbind(df.mean.increasing.roc1,
                             df.mean.increasing.roc2,
                             df.mean.increasing.roc3)
  colnames(df.mean.increasing) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.mean.increasing = subset(df.mean.increasing, select=-c(threshold2, threshold3))
  
  df.sd.increasing.roc1 = ROCcurveData(statsList[[2]][1:2], thresholds, ">")
  df.sd.increasing.roc2 = ROCcurveData(statsList[[2]][3:4],thresholds, ">")
  df.sd.increasing.roc3 = ROCcurveData(statsList[[2]][5:6],thresholds, ">")
  df.sd.increasing = cbind(df.sd.increasing.roc1,
                             df.sd.increasing.roc2,
                             df.sd.increasing.roc3)
  colnames(df.sd.increasing) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.sd.increasing = subset(df.sd.increasing, select=-c(threshold2, threshold3))
  
  df.cv.increasing.roc1 = ROCcurveData(statsList[[3]][1:2], thresholds, ">")
  df.cv.increasing.roc2 = ROCcurveData(statsList[[3]][3:4],thresholds, ">")
  df.cv.increasing.roc3 = ROCcurveData(statsList[[3]][5:6],thresholds, ">")
  df.cv.increasing = cbind(df.cv.increasing.roc1,
                             df.cv.increasing.roc2,
                             df.cv.increasing.roc3)
  colnames(df.cv.increasing) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.cv.increasing = subset(df.cv.increasing, select=-c(threshold2, threshold3))
  
  df.kurtosis.increasing.roc1 = ROCcurveData(statsList[[4]][1:2], thresholds, ">")
  df.kurtosis.increasing.roc2 = ROCcurveData(statsList[[4]][3:4],thresholds, ">")
  df.kurtosis.increasing.roc3 = ROCcurveData(statsList[[4]][5:6],thresholds, ">")
  df.kurtosis.increasing = cbind(df.kurtosis.increasing.roc1,
                             df.kurtosis.increasing.roc2,
                             df.kurtosis.increasing.roc3)
  colnames(df.kurtosis.increasing) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.kurtosis.increasing = subset(df.kurtosis.increasing, select=-c(threshold2, threshold3))
  
  df.skewness.increasing.roc1 = ROCcurveData(statsList[[5]][1:2], thresholds, ">")
  df.skewness.increasing.roc2 = ROCcurveData(statsList[[5]][3:4],thresholds, ">")
  df.skewness.increasing.roc3 = ROCcurveData(statsList[[5]][5:6],thresholds, ">")
  df.skewness.increasing = cbind(df.skewness.increasing.roc1,
                             df.skewness.increasing.roc2,
                             df.skewness.increasing.roc3)
  colnames(df.skewness.increasing) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.skewness.increasing = subset(df.skewness.increasing, select=-c(threshold2, threshold3))
  
  #constant
  df.mean.constant.roc1 = ROCcurveData(statsList[[6]][1:2], thresholds, ">")
  df.mean.constant.roc2 = ROCcurveData(statsList[[6]][3:4],thresholds, ">")
  df.mean.constant.roc3 = ROCcurveData(statsList[[6]][5:6],thresholds, ">")
  df.mean.constant = cbind(df.mean.constant.roc1,
                             df.mean.constant.roc2,
                             df.mean.constant.roc3)
  colnames(df.mean.constant) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.mean.constant = subset(df.mean.constant, select=-c(threshold2, threshold3))
  
  df.sd.constant.roc1 = ROCcurveData(statsList[[7]][1:2], thresholds, ">")
  df.sd.constant.roc2 = ROCcurveData(statsList[[7]][3:4],thresholds, ">")
  df.sd.constant.roc3 = ROCcurveData(statsList[[7]][5:6],thresholds, ">")
  df.sd.constant = cbind(df.sd.constant.roc1,
                             df.sd.constant.roc2,
                             df.sd.constant.roc3)
  colnames(df.sd.constant) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.sd.constant = subset(df.sd.constant, select=-c(threshold2, threshold3))
  
  df.cv.constant.roc1 = ROCcurveData(statsList[[8]][1:2], thresholds, ">")
  df.cv.constant.roc2 = ROCcurveData(statsList[[8]][3:4],thresholds, ">")
  df.cv.constant.roc3 = ROCcurveData(statsList[[8]][5:6],thresholds, ">")
  df.cv.constant = cbind(df.cv.constant.roc1,
                             df.cv.constant.roc2,
                             df.cv.constant.roc3)
  colnames(df.cv.constant) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.cv.constant = subset(df.cv.constant, select=-c(threshold2, threshold3))
  
  df.kurtosis.constant.roc1 = ROCcurveData(statsList[[9]][1:2], thresholds, ">")
  df.kurtosis.constant.roc2 = ROCcurveData(statsList[[9]][3:4],thresholds, ">")
  df.kurtosis.constant.roc3 = ROCcurveData(statsList[[9]][5:6],thresholds, ">")
  df.kurtosis.constant = cbind(df.kurtosis.constant.roc1,
                             df.kurtosis.constant.roc2,
                             df.kurtosis.constant.roc3)
  colnames(df.kurtosis.constant) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.kurtosis.constant = subset(df.kurtosis.constant, select=-c(threshold2, threshold3))
  
  df.skewness.constant.roc1 = ROCcurveData(statsList[[10]][1:2], thresholds, ">")
  df.skewness.constant.roc2 = ROCcurveData(statsList[[10]][3:4],thresholds, ">")
  df.skewness.constant.roc3 = ROCcurveData(statsList[[10]][5:6],thresholds, ">")
  df.skewness.constant = cbind(df.skewness.constant.roc1,
                             df.skewness.constant.roc2,
                             df.skewness.constant.roc3)
  colnames(df.skewness.constant) = c("threshold", "TPR1", "FPR1", "threshold2", "TPR2", "FPR2", "threshold3", "TPR3", "FPR3")
  df.skewness.constant = subset(df.skewness.constant, select=-c(threshold2, threshold3))
  
  return(list(df.mean.increasing,
              df.sd.increasing,
              df.cv.increasing,
              df.kurtosis.increasing,
              df.skewness.increasing,
              df.mean.constant,
              df.sd.constant,
              df.cv.constant,
              df.kurtosis.constant,
              df.skewness.constant))
}

ROCdata <- ROCdataList(statsList, thresholds)

```

## 6. ROC Plots

```{r Plots}
plotList <- function(ROCdata) {
  
}


#visual check
ROCcurve <- ggplot(data=ROCdata[[1]],
                   aes(x=FPR1, y=TPR1)) + geom_point() + geom_abline(slope=1, intercept=0, linetype=3)


# maybe works?
ROCcurve.sd.increasing <- ggplot() +
  geom_point(data=ROCdata[[2]], aes(x=FPR1, y=TPR1, color="1 year")) +
  geom_point(data=ROCdata[[2]], aes(x=FPR2, y=TPR2, color="2 years")) +
  geom_point(data=ROCdata[[2]], aes(x=FPR3, y=TPR3, color="3 years")) +
  geom_abline(slope=1, intercept=0, linetype=3)
  
```

